### PR TITLE
update deploy action to use ghcr

### PR DESCRIPTION
**Pull request by jsegal205**
Updated the deploy script to utilize github container repo. 

I stole this code from https://github.com/elixirschool/school_house/pull/228/

frank

### CODE REVIEW

**Comment by jsegal205** [comment]
@btkostner can you take a look at this and make sure that all the secrets are applied to this repo as well?

**Review by btkostner — APPROVED** [review]
Shouldn't need any new secrets as the `GITHUB_TOKEN` built in secret should have enough permissions. All looks good.

**Comment by jsegal205** [comment]
@btkostner @doomspork https://github.com/beam-community/elixir-companies/actions/runs/11407727499/job/31744528235 looks like it failed on deploy for an authentication reason. Could you take a look at the settings for actions in this repo please and let me know what I can do to help?

re - https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by btkostner** [comment]
@jsegal205 Updated and working now: https://github.com/beam-community/elixir-companies/actions/runs/11407727499/job/31745386485

**Comment by doomspork** [comment]
Thank you @jsegal205 and @btkostner! 🫶

**Pull request merged**
