### PR TITLE
Search by location together with the text search

### PR DESCRIPTION
**Pull request by cristineguadelupe**
I implemented the search by location together with the search by text, but I do not think that is the best solution. I think about creating a new "by location" search field and renaming the "text" field to "By name". Tell me what you think!

### CODE REVIEW

**Comment by bglusman** [comment]
Yeah I think this is fine, maybe worth adding some hover text or other guidance that the search will search either field but don’t think need to add a separate input

**Comment by gemantzu** [comment]
Maybe just add some placeholder text?

**Comment by cristineguadelupe** [comment]
I've added the placeholder text and also increased the text input size a little bit only for desktops to fit the entire placeholder.

**Comment by cristineguadelupe** [comment]
I added some tests following the same pattern as the previous tests. I'm new to the Elixir ecosystem, so please let me know if I'm doing something not too idiomatic.

**Pull request merged**
