### PR TITLE
chore: Update LiveDashboardHistory to hex package

### PR DESCRIPTION
**Pull request by bglusman**

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @bglusman

**Comment by bglusman** [comment]
My pleasure!

**Comment by bglusman** [comment]
Hmm..  @doomspork I'm not sure that's working right, it deployed and it shows 0.2.7 on live dashboard, but I can't click through into metrics...  may need to roll back, I dunno, or see if it works for you locally?  I'm having trouble on both master before and after that merge, so maybe something funny with my local config

**Comment by bglusman** [comment]
I rolled back the deploy on Heroku, when I run master locally it looks like a LiveView issue... this branch did upgrade LiveView to 0.14.1 so I think there must be some issue there... not sure, will update when I figure out.  Though even the rollback doesn't seem to be doing history properly, so, I don't know what's going on

**Pull request merged**
