### PR TITLE
[in-review] Fix search by company name and search by industry name

### PR DESCRIPTION
**Pull request by imahmedismail**
- Fix search by name
- Fix search by industry

### CODE REVIEW

**Comment by imahmedismail** [comment]
Please review this ? 
cc: @doomspork

**Comment by doomspork** [comment]
@imahmedismail I'm sorry 😓 I don't know how I missed the notification for this. Could we consider adding some test coverage?

**Comment by imahmedismail** [comment]
Sure @doomspork

**Comment by imahmedismail** [comment]
You can review it now.
cc: @doomspork

**Review by doomspork — APPROVED** [review]
This is wonderful, thanks for the added test coverage @imahmedismail!

**Comment by imahmedismail** [comment]
> This is wonderful, thanks for the added test coverage @imahmedismail! 

 My pleasure! @doomspork

**Pull request merged**
